import './globals.css'
import type { Metadata } from 'next'
import LeftSidebar from '@/components/LeftSidebar'
import RightSidebar from '@/components/RightSidebar'

export const metadata: Metadata = {
  title: 'CloakSpace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-row justify-between items-start'>
        <LeftSidebar/>
        <div className='bg-gray-300 min-h-screen w-[50%] overflow-hidden mx-auto'>{children}</div>
        <RightSidebar/>
      </body>
    </html>
  )
}
