import Image from 'next/image'

export default function page() {
  return (
    <div className="">
      Explore
      <ul>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
        <li>sadfadsh</li>
      </ul>
    </div>
  )
}
